variable "mongodb_public_key" {}
variable "mongodb_private_key" {}
variable "mongodb_project_id" {}
variable "mongodb_internal_group_name" {}
variable "mongodb_internal_group_metadata" {}
variable "mongodb_external_group_name" {}
variable "mongodb_external_group_metadata" {}
variable "oidc_group_alias_name" {}
variable "oidc_auth_mount_accessor" {}
variable "mongodb_role_name" {}
variable "mongodb_secrets_mount_path" {}
variable "mongodb_secrets_mount_name" {}
variable "mongodb_role_creation_statement" {}